// Created by Ronis Vision. All rights reserved
// 24.09.2020 21:40:55
// ======AUTOGENERATED - DONT EDIT======

using RVHonorAI;
using UnityEngine;
using RVModules.RVSmartAI.Content.AI.Scorers;
using RVModules.RVSmartAI.Content.AI.Scorers;
using RVHonorAI.Content.Ai.Scorers;

public abstract class CharacterScorerCurveBase : AiAgentBaseScorer
{
#region Fields
// AiAgentBaseScorerCurve
        public AnimationCurve curve = AnimationCurve.Linear(0, 0, 1, 1);
// CharacterScorer
        protected ICharacter character;
#endregion
#region Properties
// AiAgentBaseScorerCurve
// CharacterScorer
#endregion
#region Methods
// AiAgentBaseScorerCurve
        protected float GetScoreFromCurve(float _score) => curve.Evaluate(_score) * score;
// CharacterScorer
        protected override void OnContextUpdated()
        {
            base.OnContextUpdated();
            character = (Context as ICharacterProvider)?.Character;
        }
#endregion
}